config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :puzzles, only: [:index] do
    member do
      get 'second_puzzle'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_filter :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/puzzles_controller.rb
class PuzzlessController < ApplicationController
  def index
  end
end

app/views/homes/index.html.erb
<div class="row outer">
<div class="small-2 columns text-center toppart"></div>
</div>
<div class="row outer">
  <div class="small-2 columns text-center happy top"></div>
  <div class="small-2 columns text-center happy top"></div>
  <div class="small-2 columns text-center happy top"></div>
  <div class="small-2 columns text-center happy top"></div>
  <div class="small-2 columns text-center end happy top"></div>
</div>
<div class="row outer">
  <div class="small-2 columns text-center happy oneslot"></div>
  <div class="small-2 columns text-center happy twoslot"></div>
  <div class="small-2 columns text-center happy threeslot"></div>
  <div class="small-2 columns text-center happy fourslot"></div>
  <div class="small-2 columns text-center end happy fiveslot"></div>
</div>
<div class="row outer">
  <div class="small-2 columns text-center happy oneslot"></div>
  <div class="small-2 columns text-center happy twoslot"></div>
  <div class="small-2 columns text-center happy threeslot"></div>
  <div class="small-2 columns text-center happy fourslot"></div>
  <div class="small-2 columns text-center end happy fiveslot"></div>
</div>
<div class="row outer">
  <div class="small-2 columns text-center happy oneslot win"></div>
  <div class="small-2 columns text-center happy twoslot win"></div>
  <div class="small-2 columns text-center happy threeslot win"></div>
  <div class="small-2 columns text-center happy fourslot win"></div>
  <div class="small-2 columns text-center happy fiveslot win"></div>
  <div class="small-2 columns text-center dontbreak end">WIN HERE</div>
</div>
<div class="row outer">
  <div class="small-2 columns text-center happy oneslot"></div>
  <div class="small-2 columns text-center happy twoslot"></div>
  <div class="small-2 columns text-center happy threeslot"></div>
  <div class="small-2 columns text-center happy fourslot"></div>
  <div class="small-2 columns text-center end happy fiveslot"></div>
</div>
<div class="row outer">
  <div class="small-2 columns text-center happy oneslot"></div>
  <div class="small-2 columns text-center happy twoslot"></div>
  <div class="small-2 columns text-center happy threeslot"></div>
  <div class="small-2 columns text-center happy fourslot"></div>
  <div class="small-2 columns text-center end happy fiveslot"></div>
</div>
<div class="row outer">
  <div class="small-2 columns text-center happy bottom"></div>
  <div class="small-2 columns text-center happy bottom"></div>
  <div class="small-2 columns text-center happy bottom"></div>
  <div class="small-2 columns text-center happy bottom"></div>
  <div class="small-2 columns text-center end happy bottom"></div>
</div>
<div class="row">
  <div class="small-2 columns text-center"><button id='one' class="button round">1</button></div>
  <div class="small-2 columns text-center"><button id='two' class="button round">2</button></div>
  <div class="small-2 columns text-center"><button id='three' class="button round">3</button></div>
  <div class="small-2 columns text-center"><button id='four' class="button round">4</button></div>
  <div class="small-2 columns end text-center"><button id='five' class="button round">5</button></div>
</div>

<div class="row">
  <div class="small-10 columns text-center"><button class='button radius' id='reset'>Reset</button></div>
  <div id='next' class="small-10 columns text-center"><%= link_to "To the next level", puzzles_path %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puzzler</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Puzzler</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>